In [40]:
import numpy as np

In [41]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4, 8).reshape(2, 2)

print(x)
print('\n')
print(y)

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


In [42]:
print(x + y)
print(np.add(x, y))

[[ 4  6]
 [ 8 10]]
[[ 4  6]
 [ 8 10]]


In [43]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [44]:
print(x * y)
print(np.multiply(x, y))

[[ 0  5]
 [12 21]]
[[ 0  5]
 [12 21]]


In [45]:
print(x / y)
print(np.divide(x, y))

[[0.         0.2       ]
 [0.33333333 0.42857143]]
[[0.         0.2       ]
 [0.33333333 0.42857143]]


In [46]:
print(np.sqrt(x))

[[0.         1.        ]
 [1.41421356 1.73205081]]


In [47]:
print(np.exp(x)) #e

[[ 1.          2.71828183]
 [ 7.3890561  20.08553692]]


In [48]:
print(np.power(x, 2))

[[0 1]
 [4 9]]


Mean, STD, median

In [52]:
print(x)
print('\n')
print(np.mean(x, axis = 1))

[[0 1]
 [2 3]]


[0.5 2.5]


In [ ]:
print()