In [31]:
import numpy as np

In [32]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4, 8).reshape(2, 2)

print(x)
print('\n')
print(y)

[[0 1]
 [2 3]]


[[4 5]
 [6 7]]


In [33]:
print(x + y)
print(np.add(x, y))

[[ 4  6]
 [ 8 10]]
[[ 4  6]
 [ 8 10]]


In [34]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [35]:
print(x * y)
print(np.multiply(x, y))

[[ 0  5]
 [12 21]]
[[ 0  5]
 [12 21]]


In [36]:
print(x / y)
print(np.divide(x, y))

[[0.         0.2       ]
 [0.33333333 0.42857143]]
[[0.         0.2       ]
 [0.33333333 0.42857143]]
