Python list

In [13]:
import numpy as np

In [14]:
x = np.array([4, 5, 6, 7])
x

array([4, 5, 6, 7])

In [15]:
# shape
print(x.shape)

# type
print(type(x))

# dtype
print(x.dtype)

(4,)
<class 'numpy.ndarray'>
int64


In [16]:
x = np.array(['Hello', 'there'])
print(x.shape)
print(type(x))
print(x.dtype)

(2,)
<class 'numpy.ndarray'>
<U5


In [17]:
y = np.array([3, 5, 6, 'Hello'])
y

array(['3', '5', '6', 'Hello'], dtype='<U21')

In [21]:
x = np.array([[1, 3, 4], [6, 7, 8]], dtype = np.int64)
print(x)

print(x.shape)
print(type(x))
print(x.dtype)

[[1 3 4]
 [6 7 8]]
(2, 3)
<class 'numpy.ndarray'>
int64
