Numpy Funcron

In [69]:
# zeros

In [70]:
import numpy as np
import numpy.char as char

In [71]:
#Zero

x = np.zeros((3, 4), dtype=int)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
<class 'numpy.ndarray'>
int64


Ones

In [72]:
x = np.ones((3, 4), dtype=int)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
<class 'numpy.ndarray'>
int64


In [73]:
x = np.full((3, 4), 4)
print(x)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [74]:
#eye
x = np.eye((3))
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
#diag
x = np.diag((7, 8, 9))
print(x)

[[7 0 0]
 [0 8 0]
 [0 0 9]]


In [ ]:
#arange
x = np.arange(10)
print(x)

x = np.arange(4, 10)
print(x)

x = np.arange(4, 10, 2)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 6 8]


In [80]:
#radom
x = np.random.random((2, 3))
print(x)

[[0.68134931 0.23776239 0.21844011]
 [0.42050596 0.26070672 0.32410357]]


In [81]:
#randit
x = np.random.randint(2, 9, (3, 2))
print(x)

[[7 8]
 [3 6]
 [5 5]]


In [82]:
#reshape
y = np.reshape(x, (2, 3))
print(y)

[[7 8 3]
 [6 5 5]]
