In [33]:
import numpy as np

In [34]:
x = np.arange(50).reshape(5, 10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [35]:
y = x [x > 25]
print(y)

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [36]:
print(x[x <= 40])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [37]:
print(x[(x >25) & (x < 30)])

[26 27 28 29]


In [38]:
x[(x >25) & (x < 30)] = 666
print(x)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25 666 666 666 666]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]]


In [39]:
x = np.random.randint(1, 25, size = (100))
print(x)

[23  9  8 18 18  9 17 13  8 16 24 16  3 11 16  9 11 14  9  1 19 14 21 17
 16 20  9 18 22 20  8 24  4 22  3 19  7 12  4 22 14 12 10  8 22 19 15 14
 18 19 21  8 21 10  8  1  8 12 23 21  2  8  4 20  3  7 13 17 17  4  8 19
  8 17 15 14 11  9 19 17 16  4  1  5  3  1  8 15  9 18 23  2 16  9  9 10
 11  2 23 19]


In [40]:
print(x[x == 20])

[20 20 20]
