Acceder, Insertar y Eliminar elementos


In [5]:
import numpy as np

In [6]:
#acceder
x = np.array([1, 2, 3, 4])
print(x[0])
print(x[3])

print(x[-1])
print(x[-2])

1
4
4
3


In [7]:
x [0] = 30
x [-1] = 60

print(x)

[30  2  3 60]


In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

print(x[0, 1])

x[0, 1] = 10
print(x)

[[1 2 3]
 [4 5 6]]
2
[[ 1 10  3]
 [ 4  5  6]]


In [9]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0])
print(x)

[1 2 3 4 5]
[2 3 4 5]


In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

x = np.delete(x, 0, axis = 0)
print(x)

[[1 2 3]
 [4 5 6]]
[[4 5 6]]


In [11]:
x = np.array([1, 2, 3, 4])
print(x)

x = np.append(x, 5)
x = np.append(x, [6, 7])
print(x)

[1 2 3 4]
[1 2 3 4 5 6 7]


In [12]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

x = np.append(x, [[7, 8, 9]], axis = 0)
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Insert


In [13]:
x = np.array([1, 2, 3, 4])
print(x)

x = np.insert(x, 2, 5)
x = np.insert(x, 0, [10, 20])
print(x)

[1 2 3 4]
[10 20  1  2  5  3  4]


In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

x = np.insert(x, 1, 99, axis = 1)
print(x)

[[1 2 3]
 [4 5 6]]
[[ 1 99  2  3]
 [ 4 99  5  6]]


vStack

In [19]:
x = np.array([1, 2])
y = np.array([[3, 4], [5, 6]])

print(x)
print(y)

z = np.vstack((x, y))
print(z)

[1 2]
[[3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
