Acceder, Insertar y Eliminar elementos

In [2]:
import numpy as np

In [5]:
#acceder
x = np.array([1, 2, 3, 4])
print(x[0])
print(x[3])

print(x[-1])
print(x[-2])

1
4
4
3


In [ ]:
x [0] = 30
x [-1] = 60

print(x)

[30  2  3 60]


In [14]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

print(x[0, 1])

x[0, 1] = 10
print(x)

[[1 2 3]
 [4 5 6]]
2
[[ 1 10  3]
 [ 4  5  6]]


In [17]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0])
print(x)

[1 2 3 4 5]
[2 3 4 5]


In [20]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

x = np.delete(x, 0, axis = 0)
print(x)

[[1 2 3]
 [4 5 6]]
[[4 5 6]]


In [22]:
x = np.array([1, 2, 3, 4])
print(x)

x = np.append(x, 5)
x = np.append(x, [6, 7])
print(x)

[1 2 3 4]
[1 2 3 4 5 6 7]


In [28]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

x = np.append(x, [[7, 8, 9]], axis = 0)
print(x)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
