In [145]:
import numpy as np

In [146]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [147]:
z = x[0:1]
print(z)

[[0 1 2 3 4]]


In [148]:
z = x[0:2, 3:]
print(z)

[[3 4]
 [8 9]]


In [149]:
z = x[0:2, 3:4]
print(z)

[[3]
 [8]]


In [150]:
print(x)
print('\n')
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[3]
 [8]]


In [151]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [152]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [154]:
z = x [0: 2, 3:].copy()
print(z)
z[1, 1] = 999
print(z)
print('\n')
print(x)

[[3 4]
 [8 9]]
[[  3   4]
 [  8 999]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
